import type { Metadata } from 'next'
import { Inter, Permanent_Marker } from 'next/font/google'
import './globals.css'

const permanent = Permanent_Marker({ subsets: ['latin'] , weight: ['400'] , variable: '--font-permanent-marker'});
const inter = Inter({ subsets: ['latin'] , variable: '--font-inter'});

export const metadata: Metadata = {
  title: 'Welcome to SkyeGee',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${permanent.variable} ${inter.variable}`}>{children}</body>
    </html>
  )
}
